GET http://localhost:3000/boxes
Content-Type: application/json
###
POST http://localhost:3000/boxes
Content-Type: application/json
###
GET http://localhost:3000/boxes/256
Content-Type: application/json
###
GET http://localhost:3000/boxes/256
Content-Type: image/png
###
PUT http://localhost:3000/boxes/256/items
Content-Type: application/json
###