openapi: "3.0.0"
info:
  title: Tidyup api rest
  version: v1
tags:
  - name: boxes
    description: |
      Es el objeto que representa el elemento de almacenamiento del sistema. De cada uno puedes obtener los diferentes items que almacena.
x-tagGroups:
  - name: Core resources
    tags:
      - boxes
paths:
  /boxes:
    get:
      tags:
        - boxes
      summary: Buscar cajas
      description: Obtiene las distintas cajas del sistema.
      operationId: searchBoxes
      responses:
        '200':
          description: Operacion correcta
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Box'
      x-codeSamples:
        - lang: cURL
          source: |
            curl http://localhost:3000/v1/boxes

components:
  schemas:
    Id:
      type: integer
      format: int64
      readOnly: true
      example: 1
    Box:
      type: object
      properties:
        id:
          description: Box ID
          allOf:
            - $ref: '#/components/schemas/Id'
